name: Run Clang Format Test for Riggc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-test:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format
        run: pip install clang-format

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run clang-format
        run: |
          cd riggc
          clang-format --dry-run -Werror include/*.h src/*.c

