name: Run Tests for Riggc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: cd into project directory
      run: cd riggc

    - name: Run test script
      run: |
        cd riggc/tests
        ./run_tests.sh

